//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CardProto.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Card")]
  public partial class Card : global::ProtoBuf.IExtensible
  {
    public Card() {}
    
    private int _num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private string _color;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string color
    {
      get { return _color; }
      set { _color = value; }
    }
    private string _memo = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"memo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string memo
    {
      get { return _memo; }
      set { _memo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
