// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignRoomReply.proto

package org.redstone.protobuf.msg;

public interface AssignRoomReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.AssignRoomReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string address = 1;</code>
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>optional int32 roomId = 2;</code>
   */
  boolean hasRoomId();
  /**
   * <code>optional int32 roomId = 2;</code>
   */
  int getRoomId();
}
