// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleResult.proto

package org.redstone.protobuf.msg;

public final class BattleResultOuterClass {
  private BattleResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_BattleResult_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_BattleResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BattleResult.proto\022\031org.redstone.proto" +
      "buf.msg\032\013Enums.proto\"M\n\014BattleResult\022=\n\004" +
      "camp\030\001 \001(\0162%.org.redstone.protobuf.msg.E" +
      "nums.Camp:\010NoneCampB\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_org_redstone_protobuf_msg_BattleResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_redstone_protobuf_msg_BattleResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_BattleResult_descriptor,
        new java.lang.String[] { "Camp", });
    org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
