// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleResult.proto

package org.redstone.protobuf.msg;

public interface BattleResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.BattleResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isWin = 1;</code>
   */
  boolean hasIsWin();
  /**
   * <code>optional bool isWin = 1;</code>
   */
  boolean getIsWin();
}
