// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewTurnBroadcast.proto

package org.redstone.protobuf.msg;

public interface BoardSyncOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.BoardSync)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessRow rows = 1;</code>
   */
  java.util.List<org.redstone.protobuf.msg.ChessRow> 
      getRowsList();
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessRow rows = 1;</code>
   */
  org.redstone.protobuf.msg.ChessRow getRows(int index);
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessRow rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessRow rows = 1;</code>
   */
  java.util.List<? extends org.redstone.protobuf.msg.ChessRowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessRow rows = 1;</code>
   */
  org.redstone.protobuf.msg.ChessRowOrBuilder getRowsOrBuilder(
      int index);
}
