// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoardSync.proto

package org.redstone.protobuf.msg;

public interface ChessPlaceStatisticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.ChessPlaceStatistics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 num = 1;</code>
   *
   * <pre>
   * 棋子编号
   * </pre>
   */
  boolean hasNum();
  /**
   * <code>optional int32 num = 1;</code>
   *
   * <pre>
   * 棋子编号
   * </pre>
   */
  int getNum();

  /**
   * <code>optional float ratio = 2;</code>
   *
   * <pre>
   * 棋子放置率
   * </pre>
   */
  boolean hasRatio();
  /**
   * <code>optional float ratio = 2;</code>
   *
   * <pre>
   * 棋子放置率
   * </pre>
   */
  float getRatio();
}
