// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginReply.proto

package org.redstone.protobuf.msg;

public interface LoginReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.LoginReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 level = 2;</code>
   */
  boolean hasLevel();
  /**
   * <code>optional int32 level = 2;</code>
   */
  int getLevel();
}
