// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewTurnBroadcast.proto

package org.redstone.protobuf.msg;

public interface NewTurnBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.NewTurnBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .org.redstone.protobuf.msg.Enums.Camp camp = 1 [default = NoneCamp];</code>
   */
  boolean hasCamp();
  /**
   * <code>optional .org.redstone.protobuf.msg.Enums.Camp camp = 1 [default = NoneCamp];</code>
   */
  org.redstone.protobuf.msg.Enums.Camp getCamp();

  /**
   * <code>optional .org.redstone.protobuf.msg.BoardSync boardSync = 2;</code>
   */
  boolean hasBoardSync();
  /**
   * <code>optional .org.redstone.protobuf.msg.BoardSync boardSync = 2;</code>
   */
  org.redstone.protobuf.msg.BoardSync getBoardSync();
  /**
   * <code>optional .org.redstone.protobuf.msg.BoardSync boardSync = 2;</code>
   */
  org.redstone.protobuf.msg.BoardSyncOrBuilder getBoardSyncOrBuilder();
}
