// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewTurnBroadcast.proto

package org.redstone.protobuf.msg;

public final class NewTurnBroadcastOuterClass {
  private NewTurnBroadcastOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_NewTurnBroadcast_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_NewTurnBroadcast_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026NewTurnBroadcast.proto\022\031org.redstone.p" +
      "rotobuf.msg\032\013Enums.proto\"Q\n\020NewTurnBroad" +
      "cast\022=\n\004camp\030\001 \001(\0162%.org.redstone.protob" +
      "uf.msg.Enums.Camp:\010NoneCampB\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_org_redstone_protobuf_msg_NewTurnBroadcast_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_redstone_protobuf_msg_NewTurnBroadcast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_NewTurnBroadcast_descriptor,
        new java.lang.String[] { "Camp", });
    org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
