// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlaceStatisticsSync.proto

package org.redstone.protobuf.msg;

public final class PlaceStatisticsSyncOuterClass {
  private PlaceStatisticsSyncOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_PlaceStatisticsSync_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_PlaceStatisticsSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031PlaceStatisticsSync.proto\022\031org.redston" +
      "e.protobuf.msg\"2\n\024ChessPlaceStatistics\022\013" +
      "\n\003num\030\001 \001(\005\022\r\n\005ratio\030\002 \001(\002\"Z\n\023PlaceStati" +
      "sticsSync\022C\n\nstatistics\030\001 \003(\0132/.org.reds" +
      "tone.protobuf.msg.ChessPlaceStatisticsB\002" +
      "P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_descriptor,
        new java.lang.String[] { "Num", "Ratio", });
    internal_static_org_redstone_protobuf_msg_PlaceStatisticsSync_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_redstone_protobuf_msg_PlaceStatisticsSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_PlaceStatisticsSync_descriptor,
        new java.lang.String[] { "Statistics", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
