// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlaceRequest.proto

package org.redstone.protobuf.msg;

public interface PlaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.PlaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 chessNum = 1;</code>
   */
  boolean hasChessNum();
  /**
   * <code>optional int32 chessNum = 1;</code>
   */
  int getChessNum();
}
