// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlaceStatisticsSync.proto

package org.redstone.protobuf.msg;

public interface PlaceStatisticsSyncOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.PlaceStatisticsSync)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessPlaceStatistics statistics = 1;</code>
   */
  java.util.List<org.redstone.protobuf.msg.ChessPlaceStatistics> 
      getStatisticsList();
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessPlaceStatistics statistics = 1;</code>
   */
  org.redstone.protobuf.msg.ChessPlaceStatistics getStatistics(int index);
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessPlaceStatistics statistics = 1;</code>
   */
  int getStatisticsCount();
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessPlaceStatistics statistics = 1;</code>
   */
  java.util.List<? extends org.redstone.protobuf.msg.ChessPlaceStatisticsOrBuilder> 
      getStatisticsOrBuilderList();
  /**
   * <code>repeated .org.redstone.protobuf.msg.ChessPlaceStatistics statistics = 1;</code>
   */
  org.redstone.protobuf.msg.ChessPlaceStatisticsOrBuilder getStatisticsOrBuilder(
      int index);
}
