// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlaceReply.proto

package org.redstone.protobuf.msg;

public interface PlaceReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.PlaceReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>optional int32 result = 1;</code>
   */
  int getResult();
}
