// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginRequest.proto

package org.redstone.protobuf.msg;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string deviceUID = 1;</code>
   */
  boolean hasDeviceUID();
  /**
   * <code>optional string deviceUID = 1;</code>
   */
  java.lang.String getDeviceUID();
  /**
   * <code>optional string deviceUID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceUIDBytes();
}
