// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginRequest.proto

package org.redstone.protobuf.msg;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 deviceUID = 1;</code>
   */
  boolean hasDeviceUID();
  /**
   * <code>optional int64 deviceUID = 1;</code>
   */
  long getDeviceUID();
}
