// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignRoomRequest.proto

package org.redstone.protobuf.msg;

public interface AssignRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.AssignRoomRequest)
    com.google.protobuf.MessageOrBuilder {
}
