// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoardSync.proto

package org.redstone.protobuf.msg;

public final class BoardSyncOuterClass {
  private BoardSyncOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_ChessRow_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_ChessRow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_BoardSync_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_BoardSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BoardSync.proto\022\031org.redstone.protobuf" +
      ".msg\032\013Enums.proto\"E\n\010ChessRow\0229\n\005types\030\001" +
      " \003(\0162*.org.redstone.protobuf.msg.Enums.C" +
      "hessType\"2\n\024ChessPlaceStatistics\022\013\n\003num\030" +
      "\001 \001(\005\022\r\n\005ratio\030\002 \001(\002\"\203\001\n\tBoardSync\0221\n\004ro" +
      "ws\030\001 \003(\0132#.org.redstone.protobuf.msg.Che" +
      "ssRow\022C\n\nstatistics\030\002 \003(\0132/.org.redstone" +
      ".protobuf.msg.ChessPlaceStatisticsB\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_org_redstone_protobuf_msg_ChessRow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_redstone_protobuf_msg_ChessRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_ChessRow_descriptor,
        new java.lang.String[] { "Types", });
    internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_ChessPlaceStatistics_descriptor,
        new java.lang.String[] { "Num", "Ratio", });
    internal_static_org_redstone_protobuf_msg_BoardSync_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_redstone_protobuf_msg_BoardSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_BoardSync_descriptor,
        new java.lang.String[] { "Rows", "Statistics", });
    org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
