// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoardSync.proto

package org.redstone.protobuf.msg;

public interface ChessRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.ChessRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.redstone.protobuf.msg.Enums.ChessType types = 1;</code>
   */
  java.util.List<org.redstone.protobuf.msg.Enums.ChessType> getTypesList();
  /**
   * <code>repeated .org.redstone.protobuf.msg.Enums.ChessType types = 1;</code>
   */
  int getTypesCount();
  /**
   * <code>repeated .org.redstone.protobuf.msg.Enums.ChessType types = 1;</code>
   */
  org.redstone.protobuf.msg.Enums.ChessType getTypes(int index);
}
