// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enums.proto

package org.redstone.protobuf.msg;

public interface EnumsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.Enums)
    com.google.protobuf.MessageOrBuilder {
}
