// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinRoomReply.proto

package org.redstone.protobuf.msg;

public final class JoinRoomReplyOuterClass {
  private JoinRoomReplyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_redstone_protobuf_msg_JoinRoomReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_redstone_protobuf_msg_JoinRoomReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023JoinRoomReply.proto\022\031org.redstone.prot" +
      "obuf.msg\032\017BoardSync.proto\032\013Enums.proto\"\215" +
      "\001\n\rJoinRoomReply\0223\n\004camp\030\001 \001(\0162%.org.red" +
      "stone.protobuf.msg.Enums.Camp\022\016\n\006roomId\030" +
      "\002 \001(\005\0227\n\tboardSync\030\003 \001(\0132$.org.redstone." +
      "protobuf.msg.BoardSyncB\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.redstone.protobuf.msg.BoardSyncOuterClass.getDescriptor(),
          org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_org_redstone_protobuf_msg_JoinRoomReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_redstone_protobuf_msg_JoinRoomReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_redstone_protobuf_msg_JoinRoomReply_descriptor,
        new java.lang.String[] { "Camp", "RoomId", "BoardSync", });
    org.redstone.protobuf.msg.BoardSyncOuterClass.getDescriptor();
    org.redstone.protobuf.msg.EnumsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
