// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinRoomRequest.proto

package org.redstone.protobuf.msg;

public interface JoinRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.JoinRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string deviceUID = 1;</code>
   */
  boolean hasDeviceUID();
  /**
   * <code>optional string deviceUID = 1;</code>
   */
  java.lang.String getDeviceUID();
  /**
   * <code>optional string deviceUID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceUIDBytes();

  /**
   * <code>optional int32 roomId = 2;</code>
   */
  boolean hasRoomId();
  /**
   * <code>optional int32 roomId = 2;</code>
   */
  int getRoomId();
}
