// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinBattleRequest.proto

package org.redstone.protobuf.msg;

public interface JoinBattleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.redstone.protobuf.msg.JoinBattleRequest)
    com.google.protobuf.MessageOrBuilder {
}
